Add RickDBCN email to plugins
filamentphp/filamentphp.com pull request #104
Opened 2023-08-08 08:46 UTC by RickDBCN

2023-08-08 08:49 UTC, pxlrbt commented
Is this really a widget and action? I think `panel-builder` is the better category. Or does the action can be used on its own?

2023-08-08 08:52 UTC, RickDBCN commented
> Is this really a widget and action? I think `panel-builder` is the better category. Or does the action can be used on its own?

You are correct. Fixed!

2023-08-08 11:23 UTC, sacalito approved these changes

2023-08-08 11:31 UTC, sacalito commented
sorry clicked by error, please remove the approved changes and this coment

2023-08-12 08:50 UTC, danharrin requested changes

2023-08-12 08:50 UTC, danharrin commented on content/plugins/rickdbcn-email
> +docs_url: https://github.com/RickDBCN/filament-email/blob/main/README.md
This needs to be the raw markdown file path, like in our README example

2023-08-14 07:23 UTC, merged

2023-08-14 07:23 UTC, danharrin commented
Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.