[New Plugin] Jobs monitor
filamentphp/filamentphp.com pull request #109
Opened 2023-08-09 14:06 UTC by croustibat

Hi,
Here is the request for Jobs monitor plugin for Filament V2 (soon V3).

2023-08-12 08:57 UTC, danharrin requested changes

2023-08-12 08:57 UTC, danharrin commented on content/plugins/croustibat-jobs-monitor.md
> +publish_date: 2023-08-09
Please fix this so that it is the date of the first release of your plugin, rather than the date you submitted it here.

2023-08-12 08:57 UTC, danharrin commented on content/plugins/croustibat-jobs-monitor.md
> +description: Queue Monitoring Package for Filament
```suggestion
description: Monitor your queues from a panel
```

2023-08-12 08:57 UTC, danharrin commented on content/plugins/croustibat-jobs-monitor.md
> +categories: [developer-tools, analytics]
```suggestion
categories: [developer-tools, panel-builder]
```

2023-08-14 08:14 UTC, croustibat commented on content/plugins/croustibat-jobs-monitor.md
> +categories: [developer-tools, analytics]
done !

2023-08-14 08:30 UTC, merged

2023-08-14 08:30 UTC, danharrin commented
Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.