password reveal input
filamentphp/filamentphp.com pull request #111
Opened 2023-08-10 01:19 UTC by phpsa

2023-08-12 09:05 UTC, danharrin requested changes

2023-08-12 09:05 UTC, danharrin commented on content/plugins/craig-g-smith-password-reveal.md
> +name: Filament Password Input
```suggestion
name: Password Input
```

2023-08-12 09:05 UTC, danharrin commented on content/plugins/craig-g-smith-password-reveal.md
> +categories: [form-field]
```suggestion
categories: [form-builder, form-field]
```

2023-08-12 09:05 UTC, danharrin commented on content/plugins/craig-g-smith-password-reveal.md
> +discord_url:
```suggestion
discord_url: https://discord.com/channels/883083792112300104/970412812990033971
```

2023-08-12 09:05 UTC, danharrin commented on content/plugins/images/craig-g-smith-filament-password-reveal.png
I believe this may be too wide for our website and will be cropped?

2023-08-12 21:59 UTC, phpsa commented on content/plugins/images/craig-g-smith-filament-password-reveal.png
Thanks, Updated with your suggestions.

2023-08-13 20:27 UTC, danharrin commented
Sorry, that image is still too wide. It should be 16:9 to fit on the website. ATM, it would get cropped like this, which we would not publish

<img width="1184" alt="Screenshot 2023-08-13 at 21 26 55" src="https://github.com/filamentphp/filamentphp.com/assets/41773797/c7e5ec1f-606e-4a4d-a06f-990931f49029">

2023-08-23 11:41 UTC, danharrin commented
Hi @phpsa did you see my comment above?

2023-08-23 12:13 UTC, pxlrbt commented
@danharrin Btw. there is also an open PR for revealable password fields in core: https://github.com/filamentphp/filament/pull/7492#issuecomment-1683714571

2023-08-23 12:20 UTC, danharrin commented
yeah, this plugin can still be discoverable for v2 users though. not even sure if I like that PR really

2023-10-28 09:47 UTC, danharrin commented
No updates, please reopen this when you fix https://github.com/filamentphp/filamentphp.com/pull/111#issuecomment-1676455219

2023-10-28 09:47 UTC, closed without merging