Addition of the "Filament-Tour" plugin
filamentphp/filamentphp.com pull request #137
Opened 2023-08-20 14:08 UTC by JibayMcs

![jibay-mcs-tour](https://github.com/filamentphp/filamentphp.com/assets/7621593/6fa1eba3-693f-41be-8f6a-0bebe8bcb0c4)

Hi !

Just a simple plugin to wrap [DriverJS](https://driverjs.com) in your Filament app, and create Tours and Highlight some elements to guide users through your dashboard.

[+ More informations](https://github.com/JibayMcs/filament-tour/blob/3.x/README.md) (https://github.com/JibayMcs/filament-tour/blob/3.x/README.md)

2023-08-23 12:35 UTC, danharrin requested changes

2023-08-23 16:08 UTC, JibayMcs commented on content/plugins/jibay-mcs-tour.md
> +docs_url: https://github.com/JibayMcs/filament-tour/blob/3.x/README.md
Opps !
Thank for your feedback
Done ! :)

2023-08-28 06:31 UTC, danharrin requested changes

2023-08-28 06:31 UTC, danharrin commented on content/plugins/images/jibay-mcs-tour.jpg
I appreciate the effort that was put in here, however the design does look quite different to the other plugins on our website, and that contrast might put users off from clicking on it. Maybe you could have a look at the other plugins that are on our website for style inspiration? It's up to you if you want to redesign it or not, please let me know if you want to proceed and I will publish it as-is.

2023-08-28 06:31 UTC, danharrin commented on content/authors/jibay-mcs.md
> +Just an old lumberjack, playing with Laravel
Could you add a little bit more of a bio here, so it's similar to the others on our website?

2023-09-04 11:42 UTC, merged