=added gRecaptcha and PhoneField plugins
filamentphp/filamentphp.com pull request #139
Opened 2023-08-21 11:57 UTC by AbanoubNassem

2023-08-28 06:42 UTC, danharrin requested changes

2023-08-28 06:42 UTC, danharrin commented on content/plugins/filament-grecaptcha-field.md
Please do not include the word "Filament" in the `name` or `slug` of your plugin, or the file names. It is redundant, as all plugins on the website are for Filament.

2023-08-28 06:42 UTC, danharrin commented on content/plugins/filament-grecaptcha-field.md
> +discord_url:
```suggestion
discord_url: https://discord.com/channels/883083792112300104/1034067339190210611
```

2023-08-28 06:42 UTC, danharrin commented on content/plugins/filament-grecaptcha-field.md
> +image: https://cloud.githubusercontent.com/assets/1529454/5291635/1c426412-7b88-11e4-8d16-46161a081ece.gif
Please put images in the correct directory, as per our README instructions.

2023-09-16 13:46 UTC, AbanoubNassem commented on content/plugins/filament-grecaptcha-field.md
sure , done.

2023-10-15 19:19 UTC, danharrin requested changes

2023-10-15 19:19 UTC, danharrin commented on content/plugins/images/grecaptcha-field.gif
This image is not the correct dimensions, it will be badly cropped on our website. Please read the README instructions. Also, we do not currently support GIFs.

2023-10-15 19:19 UTC, danharrin commented on content/plugins/phone-field.md
We will need an image for this plugin

2023-11-23 02:30 UTC, saade requested changes
Hey! Your author image dimensions must be at least 1000x1000px as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#setting-up-an-author-profile), please mark this PR as ready for review when ready.

2023-11-25 18:55 UTC, saade approved these changes

2023-11-25 18:56 UTC, merged