Adds Shane Rosenthal contributor and Panel Roles plugin
filamentphp/filamentphp.com pull request #186
Opened 2023-09-22 14:49 UTC by shanerbaner82

2023-10-02 19:01 UTC, saade requested changes

2023-10-02 19:01 UTC, saade commented on content/plugins/shane-rosenthal-panel-roles.md
Please do not include the word "Filament" in the name or slug of your plugin, or the file names. It is redundant, as all plugins on the website are for Filament.

2023-10-02 19:07 UTC, saade requested changes

2023-10-02 19:07 UTC, saade commented on content/plugins/shane-rosenthal-panel-roles.md
> +slug: filament-panel-roles
```suggestion
slug: shanerbaner82-panel-roles
```

2023-10-03 18:12 UTC, shanerbaner82 commented on content/plugins/shane-rosenthal-panel-roles.md
I think your suggestion fixed it, right?

2023-10-03 19:01 UTC, saade commented on content/plugins/shane-rosenthal-panel-roles.md
Yes it does, just explaining why i've made the suggestion

2023-10-09 18:55 UTC, shanerbaner82 commented on content/authors/shane-rosenthal.md
> +avatar: laravelonline.jpeg
Updated, good catch.

2023-10-09 19:03 UTC, awcodes approved these changes

2023-10-15 20:23 UTC, danharrin commented
Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.

2023-10-15 20:28 UTC, merged