add filament-users plugin and my author profile
filamentphp/filamentphp.com pull request #195
Opened 2023-09-28 13:07 UTC by 3x1io

2023-10-02 19:03 UTC, saade commented on content/plugins/filament-translations.md
> +name: Filament Users
```suggestion
name: Translations
```

2023-10-02 19:04 UTC, saade requested changes
Please do not include the word "Filament" in the name or slug of your plugin, or the file names. It is redundant, as all plugins on the website are for Filament.

2023-10-02 19:04 UTC, saade commented on content/plugins/filament-translations.md
> +slug: filament-translations
```suggestion
slug: fadymondy-translations
```

2023-10-02 19:04 UTC, saade commented on content/plugins/filament-users.md
> +name: Filament Users
```suggestion
name: Users
```

2023-10-02 19:04 UTC, saade commented on content/plugins/filament-users.md
> +slug: filament-users
```suggestion
slug: fadymondy-users
```

2023-10-03 07:59 UTC, 3x1io commented
Oky i will on the next plugins

2023-10-03 15:11 UTC, saade commented
> Oky i will on the next plugins

this plugin will not be accepted if it does not follow the [plugin guidelines](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin). You don't need to accept exacly my suggestions, just make sure to not include the word `Filament` in your plugin name or slug.

2023-10-04 07:09 UTC, 3x1io commented
np i will fixit and resubmit, thanks

2023-10-15 20:44 UTC, closed without merging

2023-10-15 20:44 UTC, danharrin commented
Please reopen when you have fixed it.