add swiper plugin
filamentphp/filamentphp.com pull request #225
Opened 2023-11-05 02:37 UTC by rupadana

2023-11-05 17:31 UTC, awcodes requested changes

2023-11-05 17:31 UTC, awcodes commented on content/plugins/rupadana-swiper.md
> +slug: swiper
Please rename slug to 'rupadana-swiper'.

2023-11-05 17:31 UTC, awcodes commented on content/plugins/rupadana-swiper.md
> +discord_url: https://discord.com/channels/883083792112300104/1080807837833384017
Leave the 'discord_url' empty for now.

2023-11-05 17:31 UTC, awcodes commented on content/plugins/rupadana-swiper.md
> +image: rupadana-filament-swiper.png
Remove 'image' key, this will be automatically generated.

But you do need to rename your image file to 'rupadana-swiper.png'

2023-11-06 02:49 UTC, rupadana commented
done. please review it again @awcodes

2023-11-06 13:48 UTC, awcodes approved these changes

2023-11-23 01:13 UTC, saade approved these changes
Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.

2023-11-23 01:14 UTC, saade requested changes
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

2023-11-23 08:03 UTC, rupadana commented
i've changed the image url on my plugin README, please review it again thanks. @saade

2023-11-23 14:41 UTC, saade approved these changes
Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.

2023-11-23 14:41 UTC, merged