Adds the Filament Timesheet plugin
filamentphp/filamentphp.com pull request #239
Opened 2023-11-19 16:58 UTC by timwassenburg

2023-11-22 23:46 UTC, saade requested changes
Hey! Your plugin doesn't have an image, please add images as per our [Contributing guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin). They are mandatory. For plugins, you could use [Beyond Code's banner generator](https://banners.beyondco.de) to generate them.

Also, could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

2023-11-23 07:02 UTC, timwassenburg commented
Hey Saade, thanks for the review! I added an image for the plugin and made the URL absolute of the image in the plugin's README, as requested. Please let me know if there's anything else.

2023-11-23 14:35 UTC, saade approved these changes

2023-11-23 14:35 UTC, merged

2023-11-23 14:37 UTC, saade commented
Your plugin's `README` is loaded into the plugin page on the Filament website. There is now a duplicate image on your page, as it also exists in your documentation. You can remove it from the Filament website by giving it a `filament-hidden` class, so then it is only shown once.