added plugin: input-select-affix, as well as author page
filamentphp/filamentphp.com pull request #241
Opened 2023-11-22 12:41 UTC by marvinosswald

2023-11-22 23:21 UTC, saade requested changes
Hey! Your plugin doesn't have an image, please add images as per our [Contributing guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin). They are mandatory. For plugins, you could use [Beyond Code's banner generator](https://banners.beyondco.de) to generate them.

2023-11-22 23:26 UTC, saade commented on content/plugins/marvinosswald-input-select-affix.md
> +description: this input enables you to render a select next to an input in a seamless fashion.
```suggestion
description: This input enables you to render a select next to an input in a seamless fashion.
```

2023-11-22 23:26 UTC, saade commented on content/plugins/marvinosswald-input-select-affix.md
> +publish_date: 2023-11-22
```suggestion
publish_date: 2023-11-21
```

2023-11-23 09:23 UTC, marvinosswald commented
Sorry i missed this, prepared the image already but then forgot to add it. Thank you !

2023-11-23 14:57 UTC, saade approved these changes

2023-11-23 14:57 UTC, merged