[Plugin] Sellarix - Fillament Blog Plugin
filamentphp/filamentphp.com pull request #272
Opened 2023-12-17 12:39 UTC by daniel-sellarix

This package provides a full blog module for both frontend livewire components and backend filament management

Functionality available:

- Multiple Post Types
- Blog Categories
- Blog Posts
- Blog Tags
- Author Connection
- Latest Posts
- Widget for latest posts

2023-12-18 09:50 UTC, saade requested changes
Hey! You're missing your author image, it must fit the 1:1 aspect ratio, at least 1000x1000 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#setting-up-an-author-profile).

Please let us know when you've addressed these issues.

2023-12-19 22:01 UTC, saade requested changes
Hey! Could you please remove this part from your readme? It looks like it shouldn't be there.

<img width="780" alt="image" src="https://github.com/filamentphp/filamentphp.com/assets/14329460/d4cde10d-d44a-4b7b-a8bd-c79ed7032cf0">

Please let us know when you've addressed these issues.

2023-12-20 08:20 UTC, daniel-sellarix commented
@saade the Linkedin and github urls was supposed to be but moved them to the end to make it less confusing :D

2024-01-01 15:22 UTC, saade approved these changes

2024-02-20 00:29 UTC, merged