[Article] "Filament: What to Expect in 2024"
filamentphp/filamentphp.com pull request #294
Opened 2024-01-04 03:43 UTC by alexandersix

This is a slightly more fleshed-out version of my notes from the Filament 2024 Kickoff call. Give it a look and make sure I'm conveying everything accurately!

2024-01-04 14:33 UTC, awcodes reviewed
Looks good to me. Good job.

2024-01-04 20:54 UTC, ralphjsmit reviewed
Nice & comprehensive article!

2024-01-04 20:54 UTC, ralphjsmit commented on content/articles/alexandersix-filament-2024-goals.md
> +2023 was an incredible year for Filament, and the momentum just keeps on going into 2024! The Filament core team has taken a lot of time over the past couple of months to develop our goals for 2024,
```suggestion
2023 was an incredible year for Filament, and the momentum just keeps on going into 2024! The Filament core team has taken a lot of time over the past couple of months to develop our goals for 2024, and we're excited to share them with you here! This list was originally shared during the Filament 2024 Kickoff event, so if you want to be the first to hear about our yearly goals, make sure to tune in to our Filament 2025 Kickoff event next year!
```

2024-01-04 20:54 UTC, ralphjsmit commented on content/articles/alexandersix-filament-2024-goals.md
> +Currently, most everything that Filament's users are wanting to do in their themes can be done using the new APIs added to Filament components in v3. However, the implementation isn't as technically
```suggestion
Currently, almost everything that Filament's users are wanting to do in their themes can be done using the new APIs added to Filament components in v3. However, the implementation isn't as technically sound as we'd like. This is mostly down to the fact that, when our default styles are overridden to create themes, the original Tailwind classes are still sticking around in the class string. This has two big issues that we want to address:
```

2024-01-05 04:10 UTC, alexandersix commented
> Just casually noticed this one in the list of open PRs, nice & comprehensive article!

Thank you for all your help with the summarization, @ralphjsmit!

2024-01-07 18:48 UTC, danharrin requested changes
Please upload the original image to content/article/images. The `optimize-images` script can be used to autogenerate the WEBP version

2024-01-07 18:48 UTC, danharrin commented on content/articles/alexandersix-filament-2024-goals.md
> +The core team gained three new members in 2023: [Hassan](https://zahirnia.com/) to lead the UI/UX design for Filament, [Saade](https://github.com/saade) to revamp the plugin submission process, and [
```suggestion
The core team gained three new members in 2023: [Hassan](https://zahirnia.com) to lead the UI/UX design for Filament, [Saade](https://github.com/saade) to revamp the plugin submission process, and [Alex](https://alexandersix.com) to head up Filament's developer relations. With the new additions, Filament's core team is now made up of eight members!
```

2024-01-07 18:48 UTC, danharrin commented on content/articles/alexandersix-filament-2024-goals.md
> +- **Block Groups for Builder Fields** – organization groups for Builder blocks instead of a single dropdown list for easier block discovery
```suggestion
```

2024-01-07 18:48 UTC, danharrin commented on content/articles/alexandersix-filament-2024-goals.md
> +In the JavaScript world, [Storybook](https://storybook.js.org/) is a fantastic piece of software that helps developers view and use components within their projects. We want to create an experience s
```suggestion
In the JavaScript world, [Storybook](https://storybook.js.org) is a fantastic piece of software that helps developers view and use components within their projects. We want to create an experience similar to Storybook for our Filament UI components that allows easy copy/paste usage of the Blade components.
```

2024-01-07 18:54 UTC, danharrin commented
ignore me lol

2024-01-07 18:54 UTC, merged