Add Develogix Agency Pirsch Dashboard Widget plugin
filamentphp/filamentphp.com pull request #407
Opened 2024-05-09 15:18 UTC by DevRaeph

2024-05-09 16:51 UTC, DevRaeph commented
I've added another Plugin, so i closed the previews pull request :)

2024-05-14 21:27 UTC, saade requested changes
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues.

2024-05-14 21:37 UTC, DevRaeph commented
@saade Hey, thank you for your review. I changed the two plugin readme. 
You you please check an verify them? Thank you! :)

2024-05-21 17:23 UTC, saade approved these changes

2024-05-21 17:23 UTC, merged