[Plugin] Filament Field Group
filamentphp/filamentphp.com pull request #504
Opened 2024-08-09 06:21 UTC by lam0819

2024-08-30 16:55 UTC, saade requested changes
Hey! Your plugin image must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

Please let us know when you've addressed these issues.

2024-09-06 13:58 UTC, saade requested changes
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues. 

2024-09-09 02:14 UTC, lam0819 commented
sure and updated.

2024-09-09 15:59 UTC, saade approved these changes

2024-09-09 15:59 UTC, merged