Author Profile And Plugins
filamentphp/filamentphp.com pull request #517
Opened 2024-08-24 18:56 UTC by stephenjude

This PR contains my author profile and the following plugins:

- Blog.
- Debugger.
- Feature flags.
- Jetstream.
- Two Factor Authentication.

2024-08-24 18:57 UTC, stephenjude commented
@saade this PR is ready.

2024-08-30 18:14 UTC, saade requested changes
Hey! Could you please ensure that image URLs in your plugin's `README` file are absolute URLs rather than relative links? Then we can embed them on our website correctly. Thanks!

Please let us know when you've addressed these issues. 

2024-09-03 14:00 UTC, stephenjude commented
Done @saade

2024-09-07 23:43 UTC, saade approved these changes

2024-09-07 23:44 UTC, merged