submitting new plugin
filamentphp/filamentphp.com pull request #525
Opened 2024-08-31 14:50 UTC by CharrafiMed

2024-09-07 23:52 UTC, saade requested changes
Hey! Your plugin image must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

Please let us know when you've addressed these issues.

2024-09-08 12:30 UTC, CharrafiMed commented
> Hey! Your plugin image must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).
> 
> Please let us know when you've addressed these issues.
Hey! Sorry it was just an oversight on my own

2024-09-09 16:02 UTC, saade approved these changes

2024-09-09 16:02 UTC, merged

2024-09-10 07:59 UTC, YoussefACHCHIRAJ commented
a great and useful plugin, thanks CharrafiMed for this open source plugin, it will very helpful in my future projects