[Plugin] Add Filaletter plugin
filamentphp/filamentphp.com pull request #596
Opened 2024-11-15 04:21 UTC by lam0819

2024-12-22 21:45 UTC, saade requested changes
Please follow the documentation on how to sell a plugin. You're missing Anystack configuration.

https://github.com/filamentphp/filamentphp.com?tab=readme-ov-file#selling-a-plugin

2024-12-23 10:46 UTC, lam0819 commented
add Anystack Id now.

2025-01-05 15:36 UTC, saade commented
Hey! It doesnt look like you have opted-in to Filament as an affiliate in Anystack?

2025-01-05 15:53 UTC, lam0819 commented
> Hey! It doesnt look like you have opted-in to Filament as an affiliate in Anystack?

<img width="813" alt="image" src="https://github.com/user-attachments/assets/45d85b95-b6bd-42f4-8894-8dd2e4feeb8d" />

Applyed

2025-01-05 16:15 UTC, merged