Add niladam author & niladam-auto-logout plugin.
filamentphp/filamentphp.com pull request #603
Opened 2024-11-26 20:51 UTC by niladam

Hello,

I have created a small plugin that auto-logs out users who are afk.

Since this is my first PR & first filament plugin -- i might've skipped a few steps or broken some rules.

I did try to follow them to the best of my abilities, but just in case i missed something, i apologise in advance.

Sadly, my plugin doesn't really have the option to have such a big image since it's basically just a small bar on the left/right side of the panel with a countdown and a small text.

Would a video help ?

If that's the case, do you have any suggestions for this ?

Thank you,
Madalin.

2024-12-14 08:55 UTC, niladam commented
Hello @saade -- i'm aware you're pretty swamped but i was wondering if there's any reason for holding this up ?

Is there anything that i can do ?

2024-12-22 21:59 UTC, saade requested changes
Hey! Your plugin doesn't have an image, please add images as per our [Contributing guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin). It must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG. They are mandatory. For plugins, you could use [Beyond Code's banner generator](https://banners.beyondco.de) to generate them.

Please let us know when you've addressed these issues.

2024-12-23 18:23 UTC, niladam commented
Hello @saade -- i have added an image generated using BC's banner generator :)

Thank you for your time!:)

2025-01-05 15:39 UTC, saade approved these changes

2025-01-05 15:39 UTC, merged