[Author][Plugin] - Add Plugin Refresh Table and Author Faizan Anwer Ali
filamentphp/filamentphp.com pull request #615
Opened 2024-12-15 19:53 UTC by faizananwerali

A Filament plugin that adds refresh functionality with refresh button to tables automatically.

![Filament Refresh Table Plugin](https://github.com/user-attachments/assets/8a11c415-db87-4cf7-b810-646ae1a3b70e)

2024-12-22 22:32 UTC, saade requested changes
Hey! Your plugin image must fit the 16:9 aspect ratio, at least 2560x1440 pixels in size, and preferably a JPEG, as per our [Contributing Guide](https://github.com/filamentphp/filamentphp.com#submitting-a-plugin).

2025-01-16 08:10 UTC, faizananwerali commented
Hi @saade, I've checked and confirm image is 16:9 ratio, 922x518 pixels in size, .jpg file, file size is 18.36.

2025-01-24 10:05 UTC, faizananwerali commented
discord_url added

2025-01-31 22:55 UTC, saade commented
>at least 2560x1440 pixels in size

your image is too small.

2025-03-22 22:42 UTC, saade commented
feel free to reopen it

2025-03-22 22:42 UTC, closed without merging